name: sbusy_api
version: 0.0.1
description: Api server for SBusy

environment: 
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  intl: ^0.17.0-nullsafety.2
  json_annotation: ^3.1.1

dev_dependencies:
  test: ^1.15.7
  json_serializable: ^3.5.0
  build_runner: ^1.10.6